---

- name: Create web configuration, data, and state directories
  file:
    path: "{{ item.path }}"
    owner: "{{ item.owner | default(omit) }}"
    group: "{{ item.group | default(omit) }}"
    mode: "{{ item.mode | default(omit) }}"
    state: directory
  with_items:
    - path: "{{ mailman3_etc_dir }}"
      group: "{{ __mailman3_group_name }}"
      mode: "0770"
    - path: "{{ mailman3_django_var_dir }}"
      owner: "{{ mailman3_web_user }}"
      group: "{{ mailman3_web_group }}"
    - path: "{{ mailman3_django_var_dir }}/run"
      owner: "{{ mailman3_web_user }}"
      group: "{{ mailman3_web_group }}"
      mode: "0750"
    - path: "{{ mailman3_django_var_dir }}/db"
      owner: "{{ mailman3_web_user }}"
      group: "{{ mailman3_web_group }}"
      mode: "0750"
    - path: "{{ mailman3_django_var_dir }}/fulltext_index"
      owner: "{{ mailman3_web_user }}"
      group: "{{ mailman3_web_group }}"
      mode: "0750"
    - path: "{{ mailman3_django_var_dir }}/emails"
      owner: "{{ mailman3_web_user }}"
      group: "{{ mailman3_web_group }}"
      mode: "0750"
    - path: "{{ mailman3_django_project_dir }}"
      owner: "{{ mailman3_web_user }}"
      group: "{{ mailman3_web_group }}"
      mode: "0770"
    - path: "{{ mailman3_django_project_dir }}/views" # Add folder for customized views
    - path: "{{ mailman3_django_log_dir }}"
      mode: "0755"
      owner: "{{ mailman3_web_user }}"
      group: "{{ mailman3_web_group }}"

- name: Link attach dir to efs
  file:
    path: "{{ __mailman3_django_config_merged.hyperkitty_attachment_folder }}"
    src: "{{ efs_mount_dir }}" 
    group: "{{ mailman3_web_group }}"
    state: link 
    mode: 0770 
    owner: "{{ mailman3_web_user }}" 
  when: __mailman3_django_config_merged.hyperkitty_attachment_folder is defined and efs_mount_dir is defined
# this ^ needs to result in all contents as follows: (currently it does not)
# > drwxrwx---.  3 mailman nginx   6144 Jul 31 13:18 .
- name: Create HyperKitty attachment directory
  file:
    path: "{{ __mailman3_django_config_merged.hyperkitty_attachment_folder }}"
    owner: "{{ mailman3_web_user }}"
    group: "{{ mailman3_web_group }}"
    mode: "0770"
    state: directory
  when: __mailman3_django_config_merged.hyperkitty_attachment_folder is defined and efs_mount_dir is not defined

# If this isn't done the file will be owner by root and a 500 error will be returned
- name: Touch log file as mailman
  file:
      path: "{{ mailman3_django_log_dir }}/mailmansuite.log"
      state: touch
      owner: "{{ mailman3_web_user }}"
      group: "{{ mailman3_web_group }}"

- name: Install web systemd service unit files
  template:
    src: "{{ item.src | default(item) }}.j2"
    dest: /etc/systemd/system/{{ item.dest | default(item) }}
  loop:
    - src: mailman3-web.service
      dest: mailman3-web{{ '@' if mailman3_domains is defined else '' }}.service
  loop_control:
    label: "{{ item.dest | default(item) }}"
  when: mailman3_process_manager == 'systemd'
  notify:
    - reload systemd manager configuration
