---

- name: Install system dependencies
  package:
    name: "{{ mailman3_system_dependency_packages }}"
    enablerepo: "epel"
  when: mailman3_install_system_dependencies
  # ignore_errors: yes

# This is a separate task from the next one because `python3 -m venv` doesn't install wheel and pip needs it to build
# wheels (not strictly required, but preferred) and won't load it mid-invocation if installed during the next task
- name: Create Mailman venv
  pip:
    name: wheel
    virtualenv: "{{ mailman3_install_dir }}"
    virtualenv_python: "{{ mailman3_virtualenv_python | default(omit) }}"
    virtualenv_command: "{{ mailman3_virtualenv_command | default(omit) }}"

- name: Install rcssmin without-c-extensions (due to wheel unavailability)
  pip:
    name: "rcssmin"
    virtualenv: "{{ mailman3_install_dir }}"
    extra_args: " --install-option=\"--without-c-extensions\""

- name: Upgrade pip & setuptools to latest
  pip:
    name: 
      - pip
      - setuptools
    virtualenv: "{{ mailman3_install_dir }}"
    state: latest

- name: Install Mailman and Python dependencies
  pip:
    name: "{{ mailman3_packages + mailman3_extra_packages }}"
    virtualenv: "{{ mailman3_install_dir }}"
    state: present
    
- name: Create parent install directory
  file:
    path: "{{ mailman3_install_dir }}"
    owner: "{{ __mailman3_user_name }}"
    group: "{{ __mailman3_group_name }}"
    mode: "0755"
    state: directory

# TODO: This is needed to read settings_local.py from /etc/opt/mailman3, but will it be needed for anything else?
# TODO: config option to control this?
- name: Add web user to Mailman user group
  user:
    name: "{{ mailman3_web_user }}"
    groups: "{{ __mailman3_group_name }}"

# TODO: remove the non-instance service unit file if mailman3_domains is defined, remove the instance service unit file
